@PaxosNode_HostAddress = http://localhost:5001

GET {{PaxosNode_HostAddress}}/api/paxos/health
Accept: application/json

###

GET {{PaxosNode_HostAddress}}/api/paxos/state
Accept: application/json

###

POST {{PaxosNode_HostAddress}}/api/paxos/propose
Content-Type: application/json

{
  "value": "test-value"
}

###
